#!/usr/bin/env python3
"""
Regenerate the JP <-> US file-ID maps from the two game executables.

    python tools/gen_idmap.py jp/default.xbe us/default.xbe

Writes idmap.py-style data to stdout (see --c for a C header). Only numbers are
written; no game data or file names end up in the output.

How it works
  The game keeps one table of every file it can load from disc
  (12-byte entries: u8 directory index, ..., char *name). A file is referred to
  by its index in that table ("file ID"). The JP build has extra language
  variants (_j/_f/_g/_s/_i), so the same file has a different ID in each build.
  Files are matched by directory + name; language variants fall back to the
  English (_e) or language-less file of the other build.
"""
import re, struct, sys

def u32(b, o): return struct.unpack_from('<I', b, o)[0]

class XBE:
    def __init__(self, path):
        b = self.b = open(path, 'rb').read()
        if b[:4] != b'XBEH': raise SystemExit('%s: not an XBE' % path)
        self.base = u32(b, 0x104)
        n, sh = u32(b, 0x11C), u32(b, 0x120) - self.base
        self.secs = []
        for i in range(n):
            f, va, vs, ra, rs, nm = struct.unpack_from('<IIIIII', b, sh + i * 56)
            name = b[nm - self.base:nm - self.base + 16].split(b'\0')[0].decode()
            self.secs.append((name, va, ra, rs))
        cert = u32(b, 0x118) - self.base
        self.title_id = u32(b, cert + 8)
        self.region = u32(b, cert + 0xA0)
        self.sigkey = b[cert + 0xC0:cert + 0xD0]
    def off(self, va):
        for n, v, ra, rs in self.secs:
            if v <= va < v + rs: return ra + va - v
    def cstr(self, va):
        o = self.off(va); return self.b[o:self.b.index(b'\0', o)].decode('latin-1')
    def text(self):
        n, v, ra, rs = [s for s in self.secs if s[0] == '.text'][0]
        return v, self.b[ra:ra + rs]

def file_table(x):
    v, t = x.text()
    # cmp eax, COUNT ; mov cl, [esi + TABLE] ; ... ; mov eax, [ecx*4 + DIRS]
    m = re.search(rb'\x3d(....)\x8a\x8e(....)', t, re.S)
    if not m: raise SystemExit('file table not found')
    count, table = struct.unpack('<II', m.group(1) + m.group(2))
    m2 = re.compile(rb'\x8b\x04\x8d(....)', re.S).search(t, m.end())
    dirs = u32(m2.group(1), 0)
    D = [x.cstr(u32(x.b, x.off(dirs + 4 * i))) for i in range(64) if x.off(dirs + 4 * i)]
    out = []
    for i in range(count):
        o = x.off(table + 12 * i)
        d, name = x.b[o], u32(x.b, o + 4)
        out.append((D[d].lower(), x.cstr(name).lower()))
    return out

def header_layout(x):
    """(address, size) list of the globals stored in the save header."""
    v, t = x.text()
    m = re.search(rb'\x03\x0c\xc5(....)', t, re.S)          # add ecx, [eax*8 + SIZES]
    sizes = u32(m.group(1), 0)
    cnt = u32(re.search(rb'\x8b\x15(....)\x33\xc9', t[m.start() - 0x40:m.start()], re.S).group(1), 0)
    n = u32(x.b, x.off(cnt))
    return [(u32(x.b, x.off(sizes - 4 + 8 * i)), u32(x.b, x.off(sizes + 8 * i))) for i in range(n)]

LANGS = ('_j', '_f', '_g', '_s', '_i', '_e')
def build_map(src, dst):
    idx = {k: i for i, k in enumerate(dst)}
    res = []
    for d, n in src:
        j = idx.get((d, n))
        if j is None:
            base, ext = n.rsplit('.', 1)
            cands = []
            if base[-2:] in LANGS: cands += [base[:-2] + '_e.' + ext, base[:-2] + '.' + ext]
            else: cands += [base + '_e.' + ext]
            if base.endswith('j'): cands.append(base[:-1] + '.' + ext)   # m000_mikuj -> m000_miku
            for c in cands:
                if (d, c) in idx: j = idx[(d, c)]; break
        res.append(-1 if j is None else j)
    return res

def runs(m):
    """compress to (src_start, dst_start, length) runs"""
    out = []; i = 0
    while i < len(m):
        if m[i] < 0: i += 1; continue
        s = i
        while i + 1 < len(m) and m[i + 1] == m[i] + 1: i += 1
        out.append((s, m[s], i - s + 1)); i += 1
    return out

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    J, U = XBE(args[0]), XBE(args[1])
    assert J.title_id == U.title_id == 0x54430004, 'not Fatal Frame (54430004)'
    jt, ut = file_table(J), file_table(U)
    jh, uh = header_layout(J), header_layout(U)
    assert [s for a, s in jh] == [s for a, s in uh], 'save header layouts differ'
    j2u, u2j = runs(build_map(jt, ut)), runs(build_map(ut, jt))
    info = 'JP %d files, US %d files; header %d globals, %#x bytes' % (len(jt), len(ut), len(jh), 4 + sum(s for a, s in jh))
    if '--c' in sys.argv:
        print('/* generated by tools/gen_idmap.py - %s */' % info)
        print('#define FF_JP_FILES %d\n#define FF_US_FILES %d' % (len(jt), len(ut)))
        for nm, r in (('j2u', j2u), ('u2j', u2j)):
            print('static const unsigned short FF_%s[][3] = {' % nm.upper())
            for k in range(0, len(r), 6):
                print('  ' + ' '.join('{%d,%d,%d},' % t for t in r[k:k + 6]))
            print('};')
    else:
        print('# generated by tools/gen_idmap.py - %s' % info)
        print('JP_FILES, US_FILES = %d, %d' % (len(jt), len(ut)))
        print('J2U = %r' % (j2u,))
        print('U2J = %r' % (u2j,))
    sys.stderr.write(info + '\n')
    for nm, m, src in (('JP->US', build_map(jt, ut), jt), ('US->JP', build_map(ut, jt), ut)):
        miss = [src[i][1] for i, v in enumerate(m) if v < 0]
        sys.stderr.write('%s unmapped %d: %s\n' % (nm, len(miss), ' '.join(miss)))
